resources:
      
  - name: vijay_gitRepo
    type: GitRepo
    configuration:
      path: vijayreddy1991/windowsimage
      gitProvider: vijay
      branches: 
        include: master
        
  - name: docker_build_promote_vijay
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildNumber: 1
      buildName: dockertest
            

pipelines:
  - name: vijay_test_pipe
    configuration:
      nodePool: win_2019
#       runtime:
#          type: host
#       environmentVariables:
#         readOnly:
#           JFROG_CLI_BUILD_NAME: "PIPE-f2387"
#           JFROG_CLI_BUILD_NUMBER: 2387
    steps:

      - name: build_Docker_Image
        type: DockerBuild
        configuration:
#           environmentVariables: # optional
#             JFROG_CLI_BUILD_NAME: "PIPE-f2387"
#             JFROG_CLI_BUILD_NUMBER: 2387
          dockerFileLocation: .
          dockerFileName: Dockerfile
#           dockerImageName: pipe-master.jfrog.info:8082/docker-local/node 
#           dockerImageName: pipelines.westus.cloudapp.azure.com:8082/docker-local/node
          dockerImageName: f4580.jfrog-pipelines.com//docker-local/node
          dockerImageTag: latest
          integrations:
            - name: art_v
          inputResources:
            - name: vijay_gitRepo 
            
      - name: Push_Docker_Image
        type: DockerPush
        configuration:
#           environmentVariables: # optional
#             JFROG_CLI_BUILD_NAME: "PIPE-f2387"
#             JFROG_CLI_BUILD_NUMBER: 2387
          autoPublishBuildInfo: false #IMPORTANGT******************* : if this is true then only we need outputResource in DockerPush and no need of publishBuildInfo step
          targetRepository: docker-local #required
          integrations:
            - name: art_v 
          inputSteps:
            - name: build_Docker_Image    
#       - name: dockerPublish
#         type: PublishBuildInfo
#         configuration:
#           inputSteps:
#             - name: Push_Docker_Image
#           outputResources:
#             - name: docker_Build_vijay
#       - name: dockerPromote
#         type: PromoteBuild
#         configuration:
#           targetRepository: test-generic-local
#           inputSteps:
#             - name: dockerPublish
#           integrations:
#             - name: art_v
#           inputResources:
#             - name: docker_Build_vijay
#           outputResources:
#             - name: docker_build_promote_vijay            
